config/routes.rb
Rails.application.routes.draw do
  get 'home', to: 'player_home#index'
  resources :moves
  root to: 'games#index'
  resources :players
  resources :pieces
  resources :users
  resources :games
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end
end

app/models/move.rb
class Move < ApplicationRecord
  belongs_to :game
  belongs_to :player
end

app/controllers/moves_controller.rb
class MovesController < ApplicationController
  before_action :set_move, only: %i[ show edit update destroy ]

  # GET /moves or /moves.json
  def index
    @moves = Move.all
  end

  # GET /moves/1 or /moves/1.json
  def show
  end

  # GET /moves/new
  def new
    @move = Move.new
  end

  # GET /moves/1/edit
  def edit
  end

  # POST /moves or /moves.json
  def create
    @move = Move.new(move_params)

    respond_to do |format|
      if @move.save
        format.html { redirect_to @move, notice: "Move was successfully created." }
        format.json { render :show, status: :created, location: @move }

        # update player states
        @move.game.players.each do |p|
          p.status = (p.id == @move.player_id) ? 
            Player::STATUS_DONE :
            Player::STATUS_READY
          p.save
        end

      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @move.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /moves/1 or /moves/1.json
  def update
    respond_to do |format|
      if @move.update(move_params)
        format.html { redirect_to @move, notice: "Move was successfully updated." }
        format.json { render :show, status: :ok, location: @move }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @move.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /moves/1 or /moves/1.json
  def destroy
    @move.destroy
    respond_to do |format|
      format.html { redirect_to moves_url, notice: "Move was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_move
      @move = Move.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def move_params
      params.require(:move).permit(:turn, :orders, :game_id, :player_id)
    end
end

app/helpers/moves_helper.rb
module MovesHelper
end

app/views/moves/_form.html.erb
<%= form_with(model: move) do |form| %>
  <% if move.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(move.errors.count, "error") %> prohibited this move from being saved:</h2>

      <ul>
        <% move.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :turn %>
    <%= form.number_field :turn %>
  </div>

  <div class="field">
    <%= form.label :orders %>
    <%= form.text_area :orders %>
  </div>

  <div class="field">
    <%= form.label :game_id %>
    <%= form.text_field :game_id %>
  </div>

  <div class="field">
    <%= form.label :player_id %>
    <%= form.text_field :player_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/moves/edit.html.erb
<h1>Editing Move</h1>

<%= render 'form', move: @move %>

<%= link_to 'Show', @move %> |
<%= link_to 'Back', moves_path %>

app/views/moves/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Moves</h1>

<table class="table">
  <thead>
    <tr>
      <th scope="col">Turn</th>
      <th scope="col">Orders</th>
      <th scope="col">Game</th>
      <th scope="col">Player</th>
      <th scope="col" colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @moves.each do |move| %>
      <tr>
        <td scope="row"><%= move.turn %></td>
        <td><%= move.orders %></td>
        <td><%= link_to move.game.name, move.game %></td>
        <td><%= link_to move.player.user.name, move.player %></td>
        <td><%= link_to 'Show', move %></td>
        <td><%= link_to 'Edit', edit_move_path(move) %></td>
        <td><%= link_to 'Destroy', move, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Move', new_move_path %>

app/views/moves/new.html.erb
<h1>New Move</h1>

<%= render 'form', move: @move %>

<%= link_to 'Back', moves_path %>

app/views/moves/show.html.erb
<p id="notice"><%= notice %></p>

<h2>Move</h3>
<p>
  <strong>Turn:</strong>
  <%= @move.turn %>
</p>

<p>
  <strong>Orders:</strong>
  <%= @move.orders %>
</p>

<p>
  <strong>Game:</strong>
  <%= link_to @move.game.name, @move.game %>
</p>

<p>
  <strong>Player:</strong>
  <%= link_to @move.player.user.name, @move.player.user %> (<%= link_to @move.player.color, @move.player %>)
</p>

<%= link_to 'Edit', edit_move_path(@move) %> |
<%= link_to 'Back', moves_path %>