config/routes.rb
Rails.application.routes.draw do
  get 'home', to: 'player_home#index'
  resources :moves
  root to: 'games#index'
  resources :players
  resources :pieces
  resources :users
  resources :games
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end
end

app/models/game.rb
class Game < ApplicationRecord
  has_many :players, dependent: :destroy
  has_many :pieces, dependent: :destroy
  has_many :moves, dependent: :destroy


  # status constants
  STATUS_INVALID = 0
  STATUS_OPEN    = 1
  STATUS_CLOSED  = 2
  STATUS_PLAY    = 3
  STATUS_DONE    = 4
  STATUS_ARCHIVE = 5
  STATUS_MAX     = 5

  # validations
  validates_inclusion_of :status, :in => 1..STATUS_MAX
  # validate :has_valid_players, if: Proc.new {status == Game::STATUS_CLOSED}
  accepts_nested_attributes_for :players
  validates_associated :players


  STATUS_DESCRIPTION = %w{ INVALID Open Closed Playing Completed Archived }

  def status_description
    STATUS_DESCRIPTION[status]
  end

  def has_valid_players
    puts "players.count=#{players.count}"
    if players.count != 2 then
      errors.add :players, :too_plain,
         message: "must include White and Black (has #{players.count} players)"
    end
  end


end


# closed game players options:
#   custom validator https://guides.rubyonrails.org/active_record_validations.html#on
#   would check for special player attribute asserting there is one player W+READY and one player B+DONE
#
#
#   https://guides.rubyonrails.org/v3.2/active_record_validations_callbacks.html#working-with-validation-errors

app/controllers/games_controller.rb
class GamesController < ApplicationController
  before_action :set_game, only: %i[ show edit update destroy ]

  # GET /games or /games.json
  def index
    @games = Game.all
  end

  # GET /games/1 or /games/1.json
  def show
    @board = make_board
    user_id = session['user_id']
    @user = User.find(user_id)
    @num_moves = @game.moves.count

    @is_active_player = @game.players.any? {|p| p.user_id == user_id && p.status == Player::STATUS_READY}
    @player_id = @game.players.find {|p| p.user_id == user_id}&.id
  end

  # GET /games/new
  def new
    @game = Game.new
    @game.players.build(color: 'W', status: Player::STATUS_READY)
    @game.players.build(color: 'B', status: Player::STATUS_DONE)
  end

  # GET /games/1/edit
  def edit
  end

  # POST /games or /games.json
  def create
    @game = Game.new(game_params)
    
    puts "PARAMS"
    p params
    puts "GAME_PARAMS"
    p game_params

    user_id = session['user_id']

    respond_to do |format|
      if @game.save
        format.html { redirect_to @game, notice: "Game was successfully created." }
        format.json { render :show, status: :created, location: @game }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /games/1 or /games/1.json
  def update
    respond_to do |format|
      if @game.update(game_params)
        format.html { redirect_to @game, notice: "Game was successfully updated." }
        format.json { render :show, status: :ok, location: @game }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /games/1 or /games/1.json
  def destroy
    @game.destroy
    respond_to do |format|
      format.html { redirect_to games_url, notice: "Game was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_game
      @game = Game.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def game_params
      # params.require(:game).permit(:name, :status, :players)
      params.require(:game).permit(:name, :status,
        players_attributes: [:id, :turn, :player_id, :user_id, :color, :status]
      )
    end

    @@PIECE_MAP = {
       'r'=>'♖', 'n'=>'♘', 'b'=>'♗', 'q'=>'♕', 'k'=>'♔', 'p'=>'♙',
       'R'=>'♜', 'N'=>'♞', 'B'=>'♝', 'Q'=>'♛', 'K'=>'♚', 'P'=>'♟'
    }

    # Generate a text character for piece
    def piece_symbol(piece)
      @@PIECE_MAP[piece.player.color[0].upcase == 'W' ?
        piece.name.downcase :
        piece.name.upcase
      ]
     #  &#9820;
    end


    # Generate a text character for piece
    def piece_symbol0(piece)
      
      piece.player.color[0].upcase == 'W' ?
        piece.name.downcase :
        piece.name.upcase
    end

    # Generate a 8x8 grid containing pieces on a chessboard
    def make_board
      squares = Array.new(64)

      @game.pieces.each do |p|
        squares[position_to_ix(p.position)] = piece_symbol(p)
      end

      apply_turns squares

      # board = '='*16 + "\n"
      html_board = "<table class=chess>"

      (7..0).step(-1).each do |r|
        html_board += "<tr>"
        for c in 0..7 do
          # board += ' ' + (squares[r*8+c] || '.')
          html_board += "<td>#{squares[r*8+c]}</td>"
        end
        # board += "\n"
        html_board += "</tr>\n"
      end
      # board += '='*16 + "\n"
      html_board += "</table>\n"

    end

    def position_to_ix(position)
      r = position[1].to_i - 1
      c = position[0].ord - 'a'.ord
      r * 8 + c
    end

    def position_to_rowcol(position)
      r = position[1].to_i - 1
      c = position[0] - 'a'
      [r, c]
    end

    def row(position)
      position[1].to_i
    end

    def col(position)
      position[0] - 'a'
    end


    def apply_turns(squares)
      @game.moves.order(:turn).each do |move|
        start = position_to_ix(move.orders[0..1])
        dest  = position_to_ix(move.orders[3..4])

        squares[dest] = squares[start]
        squares[start] = nil
      end
    end

end

app/helpers/games_helper.rb
module GamesHelper
end

app/views/games/_form.html.erb
<%= form_with(model: game) do |form| %>
  <% if game.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(game.errors.count, "error") %> prohibited this game from being saved:</h2>

      <ul>
        <% game.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="container">
    <div class="field">
      <%= form.label :name %>
      <%= form.text_field :name %>
    </div>

    <div class="field">
      <%= form.label :status %>
      <%= form.select :status, 
        (1..Game::STATUS_MAX).collect {|i| [Game::STATUS_DESCRIPTION[i], i] },
        { include_blank: "Select game status..." }
        %>
    </div>
  </div>

  <%= form.fields_for :players do |form_player| %>
    <h3>Player</h3>
    <p>
    <div class="container">
      <%= form_player.label :color %>
      <%= form_player.text_field :color %>

      <%= form_player.label :user_id %>
      <%= form_player.collection_select :user_id, User.all, :id, :name %>

      <%= form_player.label :status %>
      <%= form_player.select :status,
        (1...Player::STATUS_TEXT.size).collect {|i| [Player::STATUS_TEXT[i], i] },
        { include_blank: "Select game status..." }
      %>
    </div>
    </p>
  <% end %>



  <div class="actions">
    <p>
      <%= form.submit %>
    </p>
  </div>
<% end %>

app/views/games/edit.html.erb
<h1>Editing Game</h1>

<%= render 'form', game: @game %>

<%= link_to 'Show', @game %> |
<%= link_to 'Back', games_path %>

app/views/games/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Games</h1>

<table class="table">
  <thead>
    <tr>
      <th>Name</th>
      <th>Status</th>
      <th>Players</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @games.each do |game| %>
      <tr>
        <td><%= link_to game.name, game %></td>
        <td><%= Game::STATUS_DESCRIPTION[game.status] %></td>
        <td><%= game.players.collect {|p| p.user.name }.join(", ") %></td>
        <td><%= link_to 'Edit', edit_game_path(game) %></td>
        <td><%= link_to 'Destroy', game, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Game', new_game_path %>

app/views/games/new.html.erb
<h1>New Game</h1>

<%= render 'form', game: @game %>

<%= link_to 'Back', games_path %>

app/views/games/show.html.erb
<p id="notice"><%= notice %></p>

<h2>Game</h2>
<p>
  <strong>Name:</strong>
  <%= @game.name %>
</p>

<p>
  <strong>Status:</strong>
  <%= Game::STATUS_DESCRIPTION[@game.status] %>
</p>


<h3>Players</h3>
<ul>
  <% @game.players.each do |p| %>
    <li><%= link_to p.user.name, p.user %> (<%= link_to p.color, p %>)
  <% end %>

</ul>
<h3>Board</h3>
<%= raw @board %>
<h3>Moves</h3>
<ul>
  <% @game.moves.order(:turn).each do |move| %>
    <li><%= link_to move.turn, move %>: <%= move.player.color %>: <%= move.orders %>
  <% end %>
</ul>

<% if @is_active_player then %>
  <%= form_with url: moves_path, method: :post do |form| %>

    <%= form.hidden_field "move[turn]", value: @num_moves + 1 %>
    <%= form.hidden_field "move[game_id]", value: @game.id %>
    <%= form.hidden_field "move[player_id]", value: 1 %>

    <%= form.label "move[orders]", "Move:" %>
    <%= form.text_field "move[orders]" %>

    <%= form.submit "Submit Move" %>

  <% end %>

  <% move = Move.new %>
  <%= form_with(model: move) do |form| %>
    <!-- I don't expect any of this to work. form is directed to new move. -->
    <% if move.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(move.errors.count, "error") %> prohibited this move from being saved:</h2>

        <ul>
          <% move.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <%= form.hidden_field :turn, value: @num_moves + 1 %>
    <%= form.hidden_field :game_id, value: @game.id %>
    <%= form.hidden_field :player_id, value: 1 %>

 (alternate method)
    <div class="field">
      <%= form.label :orders %>
      <%= form.text_area :orders %>
    </div>

    <div class="actions">
      <%= form.submit %>
    </div>
  <% end %>

<% end %>



<%= link_to 'Edit', edit_game_path(@game) %> |
<%= link_to 'Back', games_path %>