config/routes.rb
Rails.application.routes.draw do
  get 'home', to: 'player_home#index'
  resources :moves
  root to: 'games#index'
  resources :players
  resources :pieces
  resources :users
  resources :games
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authorize


  protected

    def authorize
      unless User.find_by(id: session[:user_id])
        redirect_to login_url, notice: "Please log in"
      end
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/application/_menu.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <%= link_to "RailsChess", home_url, class: 'navbar-brand' %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item"> <%= link_to "Games", games_url, class: 'nav-link' %> </li>
	<li class="nav-item"> <%= link_to "Users", users_url, class: 'nav-link' %> </li>
	<li class="nav-item"> <%= link_to "Players", players_url, class: 'nav-link' %> </li>
	<li class="nav-item"> <%= link_to "Moves", moves_url, class: 'nav-link' %> </li>
	<li class="nav-item"> <%= link_to "Pieces", pieces_url, class: 'nav-link' %> </li>
	<li class="nav-item"> <%= link_to "Admin", pieces_url, class: 'nav-link disabled' %> </li>
      </ul>
    </div>
  </div>
</nav>